use_frameworks!

platform :ios, '11.0'

target 'DarkMagic_Example' do
  #pod 'DarkMagic', :path => '../'

  target 'DarkMagic_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
